In [1]:
import numpy as np

In [3]:
B = np.mat([
    [1, 0],
    [0, 2],
    [-1, 4]
])
C = np.mat([
    [1, 0, -1, 1],
    [0, 1, 1, 1]
])
B * C

matrix([[ 1,  0, -1,  1],
        [ 0,  2,  2,  2],
        [-1,  4,  5,  3]])

In [7]:
D = C.T * (C * C.T).I * (B.T * B).I * B.T


[[ 0.27777778  0.11111111 -0.05555556]
 [ 0.05555556  0.05555556  0.05555556]
 [-0.22222222 -0.05555556  0.11111111]
 [ 0.33333333  0.16666667  0.        ]]


In [9]:
(C * C.T)

matrix([[3, 0],
        [0, 3]])

In [10]:
B.T * B

matrix([[ 2, -4],
        [-4, 20]])

In [12]:
from fractions import Fraction
print(Fraction(D))


TypeError: argument should be a string or a Rational instance

In [14]:
A = np.mat(
    [
        [0, 1, 2, 0, -1],
        [-1, 1, 1, 1, -1],
        [-2, 1, 0, 2, -1]
    ]
)
np.linalg.pinv(A)

matrix([[ 0.0952381 , -0.04761905, -0.19047619],
        [ 0.10714286,  0.07142857,  0.03571429],
        [ 0.30952381,  0.0952381 , -0.11904762],
        [-0.0952381 ,  0.04761905,  0.19047619],
        [-0.10714286, -0.07142857, -0.03571429]])

In [15]:
B = np.mat(
    [
        [0,1],
        [-1, 1],
        [-2, 1]
    ]
)
C = np.mat([
    [1, 0, 1, -1, 0],
    [0, 1, 2, 0, -1]
])


In [16]:
B

matrix([[ 0,  1],
        [-1,  1],
        [-2,  1]])

In [17]:
B * C

matrix([[ 0,  1,  2,  0, -1],
        [-1,  1,  1,  1, -1],
        [-2,  1,  0,  2, -1]])

In [18]:
D = C.T * (C * C.T).I * (B.T * B).I * B.T
D

matrix([[ 0.0952381 , -0.04761905, -0.19047619],
        [ 0.10714286,  0.07142857,  0.03571429],
        [ 0.30952381,  0.0952381 , -0.11904762],
        [-0.0952381 ,  0.04761905,  0.19047619],
        [-0.10714286, -0.07142857, -0.03571429]])

In [19]:
C * C.T

matrix([[3, 2],
        [2, 6]])

In [20]:
B.T * B



matrix([[ 5, -3],
        [-3,  3]])